- hosts: app
  become: true

  tasks:
    - name: Pull latest image
      command: docker pull dockerhub_username/flask-app:latest

    - name: Stop old container
      command: docker stop flask-app || true

    - name: Remove old container
      command: docker rm flask-app || true

    - name: Run container
      command: docker run -d -p 80:5000 --name flask-app dockerhub_username/my-app:latest
